locales:
  available: ["en", "vi"]
  default: "en"
users:
  email:
    max_length: 250
  name:
    max_length: 250
  paginate:
    per_page: 10
  password:
    min_length: 8
    reset_expired: 5
  phone:
    min_length: 10
    max_length: 15
